import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="#">Testing dev</a>
        </h1>


        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Shall now &rarr;</h2>
            <p>Find Next.js features and API.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>It just tesing.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Tesing paths &rarr;</h2>
            <p>
                  more coming up            
           </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
             <h1>Magima</h1>
      </footer>
    </div>
  )
}




// export const getStaticProps = async () => {
//   // This is a full server-side Node environment,
//   // which means that you can make network requests,
//   // talk to databases, read from the file-system,
//   // and do whatever you want to fetch your data.

//   return {
//     props: {
//       title: "My Amazing Startup",
//       metaContent: "Amazing SEO poetry",
//       copy:
//         "I'm in the business of making people smile. That's all I'm here for.",
//     },
//   };
// };



export const getStaticProps = async () => {
  return {
    props: {
      title: "magima",
      copy:
        "just tesing for the dev paths lets see how it goes.",
    },
    revalidate: 1, // number of seconds to wait before revalidating
  };
};